name: new_project
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python==3.8
  - matplotlib
  - opencv
  - ipykernel
  - pytorch-lightning
  - lightning-bolts
  - hydra
  - black
